/*
 * generated by Xtext 2.13.0
 */
package org.example.methods.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMethodsScopeProvider extends DelegatingScopeProvider {
}
