/**
 * generated by Xtext 2.13.0
 */
package org.example.methods.ide;

import org.example.methods.ide.AbstractMethodsIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MethodsIdeModule extends AbstractMethodsIdeModule {
}
