/**
 * generated by Xtext 2.13.0
 */
package org.example.methods.methods;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.methods.methods.Model#getMehtods <em>Mehtods</em>}</li>
 * </ul>
 *
 * @see org.example.methods.methods.MethodsPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Mehtods</b></em>' containment reference list.
   * The list contents are of type {@link org.example.methods.methods.Method}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mehtods</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mehtods</em>' containment reference list.
   * @see org.example.methods.methods.MethodsPackage#getModel_Mehtods()
   * @model containment="true"
   * @generated
   */
  EList<Method> getMehtods();

} // Model
