/**
 * generated by Xtext 2.13.0
 */
package org.example.methods.methods;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.methods.methods.Value#getValueInt <em>Value Int</em>}</li>
 *   <li>{@link org.example.methods.methods.Value#getValueOthers <em>Value Others</em>}</li>
 * </ul>
 *
 * @see org.example.methods.methods.MethodsPackage#getValue()
 * @model
 * @generated
 */
public interface Value extends EObject
{
  /**
   * Returns the value of the '<em><b>Value Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Int</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Int</em>' attribute.
   * @see #setValueInt(int)
   * @see org.example.methods.methods.MethodsPackage#getValue_ValueInt()
   * @model
   * @generated
   */
  int getValueInt();

  /**
   * Sets the value of the '{@link org.example.methods.methods.Value#getValueInt <em>Value Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Int</em>' attribute.
   * @see #getValueInt()
   * @generated
   */
  void setValueInt(int value);

  /**
   * Returns the value of the '<em><b>Value Others</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Others</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Others</em>' attribute.
   * @see #setValueOthers(String)
   * @see org.example.methods.methods.MethodsPackage#getValue_ValueOthers()
   * @model
   * @generated
   */
  String getValueOthers();

  /**
   * Sets the value of the '{@link org.example.methods.methods.Value#getValueOthers <em>Value Others</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Others</em>' attribute.
   * @see #getValueOthers()
   * @generated
   */
  void setValueOthers(String value);

} // Value
