/**
 * generated by Xtext 2.13.0
 */
package org.example.methods.ui.contentassist;

import org.example.methods.ui.contentassist.AbstractMethodsProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MethodsProposalProvider extends AbstractMethodsProposalProvider {
}
