/*
 * generated by Xtext 2.13.0
 */
package org.example.methods


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MethodsStandaloneSetup extends MethodsStandaloneSetupGenerated {

	def static void doSetup() {
		new MethodsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
