/**
 * generated by Xtext 2.13.0
 */
package org.example.methods.validation;

import org.example.methods.validation.AbstractMethodsValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MethodsValidator extends AbstractMethodsValidator {
}
