/*
 * generated by Xtext 2.13.0
 */
package org.example.methods.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.example.methods.ui.internal.MethodsActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MethodsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MethodsActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MethodsActivator activator = MethodsActivator.getInstance();
		return activator != null ? activator.getInjector(MethodsActivator.ORG_EXAMPLE_METHODS_METHODS) : null;
	}

}
