/*
 * generated by Xtext 2.13.0
 */
package org.example.methods.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.example.methods.parser.antlr.internal.InternalMethodsParser;
import org.example.methods.services.MethodsGrammarAccess;

public class MethodsParser extends AbstractAntlrParser {

	@Inject
	private MethodsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMethodsParser createParser(XtextTokenStream stream) {
		return new InternalMethodsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MethodsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MethodsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
