/**
 * generated by Xtext 2.13.0
 */
package org.example.methods.scoping;

import org.example.methods.scoping.AbstractMethodsScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MethodsScopeProvider extends AbstractMethodsScopeProvider {
}
