/**
 * generated by Xtext 2.13.0
 */
package org.example.methods.methods.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.example.methods.methods.MethodsPackage;
import org.example.methods.methods.Value;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.methods.methods.impl.ValueImpl#getValueInt <em>Value Int</em>}</li>
 *   <li>{@link org.example.methods.methods.impl.ValueImpl#getValueOthers <em>Value Others</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ValueImpl extends MinimalEObjectImpl.Container implements Value
{
  /**
   * The default value of the '{@link #getValueInt() <em>Value Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueInt()
   * @generated
   * @ordered
   */
  protected static final int VALUE_INT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getValueInt() <em>Value Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueInt()
   * @generated
   * @ordered
   */
  protected int valueInt = VALUE_INT_EDEFAULT;

  /**
   * The default value of the '{@link #getValueOthers() <em>Value Others</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueOthers()
   * @generated
   * @ordered
   */
  protected static final String VALUE_OTHERS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValueOthers() <em>Value Others</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueOthers()
   * @generated
   * @ordered
   */
  protected String valueOthers = VALUE_OTHERS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ValueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MethodsPackage.Literals.VALUE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValueInt()
  {
    return valueInt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValueInt(int newValueInt)
  {
    int oldValueInt = valueInt;
    valueInt = newValueInt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MethodsPackage.VALUE__VALUE_INT, oldValueInt, valueInt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getValueOthers()
  {
    return valueOthers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValueOthers(String newValueOthers)
  {
    String oldValueOthers = valueOthers;
    valueOthers = newValueOthers;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MethodsPackage.VALUE__VALUE_OTHERS, oldValueOthers, valueOthers));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MethodsPackage.VALUE__VALUE_INT:
        return getValueInt();
      case MethodsPackage.VALUE__VALUE_OTHERS:
        return getValueOthers();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MethodsPackage.VALUE__VALUE_INT:
        setValueInt((Integer)newValue);
        return;
      case MethodsPackage.VALUE__VALUE_OTHERS:
        setValueOthers((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MethodsPackage.VALUE__VALUE_INT:
        setValueInt(VALUE_INT_EDEFAULT);
        return;
      case MethodsPackage.VALUE__VALUE_OTHERS:
        setValueOthers(VALUE_OTHERS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MethodsPackage.VALUE__VALUE_INT:
        return valueInt != VALUE_INT_EDEFAULT;
      case MethodsPackage.VALUE__VALUE_OTHERS:
        return VALUE_OTHERS_EDEFAULT == null ? valueOthers != null : !VALUE_OTHERS_EDEFAULT.equals(valueOthers);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (valueInt: ");
    result.append(valueInt);
    result.append(", valueOthers: ");
    result.append(valueOthers);
    result.append(')');
    return result.toString();
  }

} //ValueImpl
