/**
 * generated by Xtext 2.13.0
 */
package org.example.methods;

import org.example.methods.MethodsStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MethodsStandaloneSetup extends MethodsStandaloneSetupGenerated {
  public static void doSetup() {
    new MethodsStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
