/**
 * generated by Xtext 2.13.0
 */
package org.example.methods;

import org.example.methods.AbstractMethodsRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MethodsRuntimeModule extends AbstractMethodsRuntimeModule {
}
